version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=video-gallery
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3
    ports:
    - 5672:5672
