"""empty message

Revision ID: 7f9863909887
Revises: 23c1b65b0e13
Create Date: 2021-04-25 10:18:47.302554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from video_gallery.models.types.ts_vector import TSVector

revision = '7f9863909887'
down_revision = '23c1b65b0e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('__ts_vector__', TSVector(), sa.Computed("to_tsvector('english', title || ' ' || description)", persisted=True), nullable=True))
    op.create_index('ix_video___ts_vector__', 'video', ['__ts_vector__'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video___ts_vector__', table_name='video')
    op.drop_column('video', '__ts_vector__')
    # ### end Alembic commands ###
